# Generated by Django 2.2.12 on 2020-05-28 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0006_auto_20200528_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detaroles',
            name='idRol',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='userdata.Roles', verbose_name='Identificador de Rol'),
        ),
        migrations.AlterField(
            model_name='detaroles',
            name='idUser',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='userdata.DatosUser'),
        ),
    ]
