# Generated by Django 2.2.12 on 2020-05-14 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userdata', '0003_auto_20200513_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategProye',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Languaje', models.CharField(max_length=45, null=True, verbose_name='Languaje de programación')),
                ('MotorDB', models.CharField(max_length=155, null=True, verbose_name='Base de datos usada')),
                ('Arquitectura', models.CharField(max_length=255, null=True, verbose_name='Arquitectura')),
            ],
            options={
                'verbose_name': 'Tipo de Categoria',
                'verbose_name_plural': 'Categoria',
            },
        ),
        migrations.CreateModel(
            name='TipoDocu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombToDoc', models.CharField(max_length=50, verbose_name='Nombre de tipo de documento')),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Documento',
            },
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombProy', models.CharField(max_length=255, null=True, verbose_name='Nombre del proyecto')),
                ('DescProy', models.TextField(verbose_name='Descripcion de proyecto')),
                ('imgProy', models.ImageField(default='proyec.png', upload_to='', verbose_name='Foto del proyecto')),
                ('FechaIni', models.DateTimeField(null=True)),
                ('FechaFin', models.DateTimeField(null=True)),
                ('UrlRepo', models.TextField(verbose_name='Direccion URL del proyecto')),
                ('EstaProy', models.CharField(max_length=45, verbose_name='Esta del proyecto')),
                ('idCategProye', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.CategProye', verbose_name='Identificador de CategProye')),
            ],
            options={
                'verbose_name': 'Total Proyectos',
                'verbose_name_plural': 'Proyectos',
            },
        ),
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombDocu', models.CharField(max_length=45, verbose_name='Nombre del documento')),
                ('PathDocu', models.CharField(max_length=45, verbose_name='Ruta de almacenamiento')),
                ('idProyectos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.Proyectos', verbose_name='Identificador de Proyectos')),
                ('idTipoDocu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.TipoDocu', verbose_name='Identificador de Tipodocu')),
                ('idUsuarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.DatosUser', verbose_name='Identificador de DatosUser')),
            ],
            options={
                'verbose_name': 'Documentacion de Proyecto',
                'verbose_name_plural': 'Documentos',
            },
        ),
    ]
