# Generated by Django 2.2.12 on 2020-05-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_auto_20200528_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentos',
            name='NombDocu',
            field=models.CharField(max_length=255, null=True, verbose_name='Nombre del documento'),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='PathDocu',
            field=models.FileField(null=True, upload_to='documentos/proyectos', verbose_name='Archivo'),
        ),
    ]
