# Generated by Django 2.2.12 on 2020-05-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_auto_20200528_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyectos',
            name='EstaProy',
        ),
        migrations.AddField(
            model_name='categproye',
            name='tipoproy',
            field=models.CharField(max_length=100, null=True, verbose_name='Tipo de proyecto'),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='FechaFin',
            field=models.DateField(null=True, verbose_name='Fecha de Finalización'),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='FechaIni',
            field=models.DateField(null=True, verbose_name='Fecha de Inicio'),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='imgProy',
            field=models.ImageField(null=True, upload_to='img/proyectos', verbose_name='Foto del proyecto'),
        ),
    ]
