# Generated by Django 2.2.12 on 2020-05-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0005_auto_20200528_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectos',
            name='DescProy',
            field=models.TextField(null=True, verbose_name='Descripcion de proyecto'),
        ),
    ]
