# Generated by Django 2.2.12 on 2020-05-28 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0006_auto_20200528_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categproye',
            name='Arquitectura',
            field=models.CharField(max_length=255, verbose_name='Arquitectura'),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='UrlRepo',
            field=models.TextField(null=True, verbose_name='Direccion URL del proyecto'),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='idCategProye',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.CategProye', verbose_name='Identificador de CategProye'),
        ),
    ]
