# Generated by Django 2.2.12 on 2020-05-28 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0007_auto_20200528_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectos',
            name='idCategProye',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.CategProye', verbose_name='Identificador de CategProye'),
        ),
    ]
