# Generated by Django 2.2.12 on 2020-05-28 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0009_auto_20200528_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentos',
            name='idProyectos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='proyectos.Proyectos', verbose_name='Identificador de Proyectos'),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='idTipoDocu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='proyectos.TipoDocu', verbose_name='Identificador de Tipodocu'),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='idUsuarios',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userdata.DatosUser', verbose_name='Identificador de DatosUser'),
        ),
    ]
