# Generated by Django 2.2.12 on 2020-05-29 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0010_auto_20200528_1441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentos',
            options={'verbose_name': 'Documentacion de Proyecto', 'verbose_name_plural': 'Documentos de Proyecto'},
        ),
        migrations.RenameField(
            model_name='documentos',
            old_name='PathDocu',
            new_name='documento',
        ),
        migrations.RenameField(
            model_name='documentos',
            old_name='idTipoDocu',
            new_name='idtipoDocu',
        ),
    ]
