# Generated by Django 2.2.12 on 2020-05-29 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0011_auto_20200528_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectos',
            name='NombProy',
            field=models.CharField(max_length=255, verbose_name='Nombre del proyecto'),
        ),
    ]
