# Generated by Django 2.2.12 on 2020-05-29 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0012_auto_20200528_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentos',
            name='idtipoDocu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.TipoDocu', verbose_name='Identificador de Tipodocu'),
        ),
    ]
